version: "3"

services:
  database:
    image: postgres:14.1-alpine
    container_name: ictscouts_talentpool_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresdb
    networks:
      - talentpool 

  api:
    build: ../
    container_name: ictscouts_talentpool_api
    restart: always
    ports:
      - "2030:2030"
    env_file: .env
    depends_on:
      - database
    networks:
      - talentpool

networks:
  talentpool:
