version: "3"

services:
  database:
    image: postgres:14.1-alpine
    container_name: ictscouts_talentpool_dev_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgresdb