name: Deploy to Fly

on:
  push:
    branches: [ master ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Migrate Database
        run: npx prisma migrate deploy
        
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
